PBug/Models/IssueViewModel.cs
using PBug.Data;

namespace PBug.Models
{
    public class IssueViewModel
    {
        public Issue Issue { get; set; }
        public bool IsWatching { get; set; }
    }
}

PBug/Controllers/FileController.cs
using System.IO;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PBug.Authentication;
using PBug.Data;

namespace PBug.Controllers
{
    public class FileController : Controller
    {
        private readonly PBugContext db;

        public FileController(PBugContext db)
        {
            this.db = db;
        }

        [Route("/file/{uid?}")]
        [PBugPermission("issue.view")]
        public async Task<IActionResult> Download([FromRoute] string uid)
        {
            if (Path.GetFileName(uid) != uid)
                // Something's fishy...
                return Forbid();
            IssueFile ifi = await db.IssueFiles.SingleAsync(x => x.FileId == uid);
            return File(System.IO.File.OpenRead(Path.Combine("files", uid)), "application/octet-stream", ifi.FileName);
        }
    }
}

PBug/Controllers/IssueController.cs
using System.IO;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Linq;
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PBug.Data;
using PBug.Models;
using PBug.Authentication;
using Microsoft.EntityFrameworkCore;
using PBug.Utils;
using Microsoft.AspNetCore.Http;
using System.Text.Json;

namespace PBug.Controllers
{
    public class IssueController : Controller
    {
        private readonly PBugContext Db;

        public IssueController(PBugContext db)
        {
            Db = db;
        }

        [Route("/")]
        [Route("/news/")]
        [PBugPermission("issue.news")]
        public async Task<IActionResult> News([FromQuery] string q = "watched:yes")
        {
            if (q == null) q = "";
            NewsSearchModel model = new NewsSearchModel();
            model.SearchString = q;
            IQueryable<IssueActivity> searchQuery = Db.IssueActivities
                .Include(x => x.Issue)
                    .ThenInclude(x => x.Assignee)
                .Include(x => x.Issue)
                    .ThenInclude(x => x.Project)
                .Include(x => (x as CreateIssueActivity).Assignee)
                .Include(x => (x as CreateIssueActivity).Project)
                .Include(x => (x as EditIssueActivity).NewAssignee)
                .Include(x => (x as EditIssueActivity).OldAssignee)
                .Include(x => (x as EditIssueActivity).OldProject)
                .Include(x => (x as EditIssueActivity).NewProject)
                .Include(x => x.Author);
            bool orderDescending = true;
            foreach (string sub in q.Split(' ', StringSplitOptions.RemoveEmptyEntries))
            {
                if (sub.StartsWith("#"))
                {
                    string tagName = sub.Substring(1);
                    searchQuery = searchQuery.Where(x => x.Issue.Tags.Contains(tagName, StringComparison.InvariantCultureIgnoreCase));
                }
                else if (sub.StartsWith("!#"))
                {
                    string tagName = sub.Substring(2);
                    searchQuery = searchQuery.Where(x => !x.Issue.Tags.Contains(tagName, StringComparison.InvariantCultureIgnoreCase));
                }
                else if (sub.StartsWith("status:"))
                {
                    IssueStatus status;
                    if (!Enum.TryParse(sub.Substring("status:".Length), true, out status))
                        continue;
                    searchQuery = searchQuery.Where(x => x.Issue.Status == status);
                }
                else if (sub.StartsWith("!status:"))
                {
                    IssueStatus status;
                    if (!Enum.TryParse(sub.Substring("!status:".Length), true, out status))
                        continue;
                    searchQuery = searchQuery.Where(x => x.Issue.Status != status);
                }
                else if (sub.StartsWith("project:"))
                {
                    string projectId = sub.Substring("project:".Length);
                    searchQuery = searchQuery.Where(x => x.Issue.Project.ShortProjectId == projectId);
                }
                else if (sub.StartsWith("!project:"))
                {
                    string projectId = sub.Substring("!project:".Length);
                    searchQuery = searchQuery.Where(x => x.Issue.Project.ShortProjectId != projectId);
                }
                else if (sub.StartsWith("assignee:"))
                {
                    string assigneeName = sub.Substring("assignee:".Length);
                    if (assigneeName == "me")
                    {
                        searchQuery = searchQuery.Where(x => x.Issue.Assignee != null && x.Issue.Assignee.Id == HttpContext.User.GetUserId());
                    }
                    else if (assigneeName == "none")
                    {
                        searchQuery = searchQuery.Where(x => x.Issue.Assignee == null);
                    }
                    else
                    {
                        searchQuery = searchQuery.Where(x => x.Issue.Assignee != null && x.Issue.Assignee.Username == assigneeName);
                    }
                }
                else if (sub.StartsWith("!assignee:"))
                {
                    string assigneeName = sub.Substring("!assignee:".Length);
                    if (assigneeName == "me")
                    {
                        searchQuery = searchQuery.Where(x => x.Issue.Assignee == null || x.Issue.Assignee.Id != HttpContext.User.GetUserId());
                    }
                    else if (assigneeName == "none")
                    {
                        searchQuery = searchQuery.Where(x => x.Issue.Assignee != null);
                    }
                    else
                    {
                        searchQuery = searchQuery.Where(x => x.Issue.Assignee == null || x.Issue.Assignee.Username != assigneeName);
                    }
                }
                else if (sub.StartsWith("author:"))
                {
                    string authorName = sub.Substring("author:".Length);
                    if (authorName == "me")
                    {
                        searchQuery = searchQuery.Where(x => x.Issue.Author.Id == HttpContext.User.GetUserId());
                    }
                    else
                    {
                        searchQuery = searchQuery.Where(x => x.Issue.Author.Username == authorName);
                    }
                }
                else if (sub.StartsWith("!author:"))
                {
                    string authorName = sub.Substring("!author:".Length);
                    if (authorName == "me")
                    {
                        searchQuery = searchQuery.Where(x => x.Issue.Author.Id != HttpContext.User.GetUserId());
                    }
                    else
                    {
                        searchQuery = searchQuery.Where(x => x.Issue.Author.Username != authorName);
                    }
                }
                else if (sub.StartsWith("actor:"))
                {
                    string actorName = sub.Substring("actor:".Length);
                    if (actorName == "me")
                    {
                        searchQuery = searchQuery.Where(x => x.Author.Id == HttpContext.User.GetUserId());
                    }
                    else
                    {
                        searchQuery = searchQuery.Where(x => x.Issue.Author.Username == actorName);
                    }
                }
                else if (sub.StartsWith("!actor:"))
                {
                    string actorName = sub.Substring("!actor:".Length);
                    if (actorName == "me")
                    {
                        searchQuery = searchQuery.Where(x => x.Author.Id != HttpContext.User.GetUserId());
                    }
                    else
                    {
                        searchQuery = searchQuery.Where(x => x.Issue.Author.Username != actorName);
                    }
                }
                else if (sub.StartsWith("watched:"))
                {
                    int userId = HttpContext.User.GetUserId();
                    bool watched = sub.Substring("watched:".Length) == "yes";
                    searchQuery = searchQuery.Where(x =>
                        watched == (x.Issue.AssigneeId == userId || x.Issue.Watchers.Any(w => w.WatcherId == userId)));
                }
                else if (sub.StartsWith("order:"))
                {
                    string order = sub.Substring("order:".Length);
                    if (Regex.IsMatch(order, ".*asc.*"))
                        orderDescending = false;
                }
                else if (sub.StartsWith("!"))
                {
                    searchQuery = searchQuery.Where(x => !x.Issue.Name.Contains(sub.Substring(1), StringComparison.InvariantCultureIgnoreCase));
                }
                else
                {
                    searchQuery = searchQuery.Where(x => x.Issue.Name.Contains(sub, StringComparison.InvariantCultureIgnoreCase));
                }
            }
            if (orderDescending)
                searchQuery = searchQuery.OrderByDescending(x => x.Id);
            else
                searchQuery = searchQuery.OrderBy(x => x.Id);

            model.FoundNews = await searchQuery
                .ToArrayAsync();

            return View(model);
        }

        [Route("/issues/")]
        [Route("/issues/search/")]
        [PBugPermission("issue.search")]
        public async Task<IActionResult> Search([FromQuery] string q = "watched:yes")
        {
            if (q == null) q = "";
            IssueSearchModel model = new IssueSearchModel();
            model.SearchString = q;
            IQueryable<Issue> searchQuery = Db.Issues
                .Include(x => x.Assignee)
                .Include(x => x.Project);
            bool orderDescending = true;
            foreach (string sub in q.Split(' ', StringSplitOptions.RemoveEmptyEntries))
            {
                if (sub.StartsWith("#"))
                {
                    string tagName = sub.Substring(1);
                    searchQuery = searchQuery.Where(x => x.Tags.Contains(tagName, StringComparison.InvariantCultureIgnoreCase));
                }
                else if (sub.StartsWith("!#"))
                {
                    string tagName = sub.Substring(2);
                    searchQuery = searchQuery.Where(x => !x.Tags.Contains(tagName, StringComparison.InvariantCultureIgnoreCase));
                }
                else if (sub.StartsWith("status:"))
                {
                    IssueStatus status;
                    if (!Enum.TryParse(sub.Substring("status:".Length), true, out status))
                        continue;

PBug/Views/Issue/ActivityPartial.cshtml
@model IssueActivity

@functions{
    void DisplayDiff(List<DiffPlex.DiffBuilder.Model.DiffPiece> lines, bool isold) {
        foreach (var row in lines)
        {
            if (!isold)
                switch (row.Type)
                {
                    case DiffPlex.DiffBuilder.Model.ChangeType.Modified:
                    case DiffPlex.DiffBuilder.Model.ChangeType.Inserted:
                        <text><div class="smallmargin afteredit">@row.Text</div></text>
                        break;
                    case DiffPlex.DiffBuilder.Model.ChangeType.Deleted:
                    case DiffPlex.DiffBuilder.Model.ChangeType.Imaginary:
                        <text><div class="smallmargin filler"></div></text>
                        break;
                    case DiffPlex.DiffBuilder.Model.ChangeType.Unchanged:
                        <text><div class="smallmargin">@row.Text</div></text>
                        break;
                    default:
                        break;
                }
            else
                switch (row.Type)
                {
                    case DiffPlex.DiffBuilder.Model.ChangeType.Modified:
                    case DiffPlex.DiffBuilder.Model.ChangeType.Deleted:
                        <text><div class="smallmargin beforeedit">@row.Text</div></text>
                        break;
                    case DiffPlex.DiffBuilder.Model.ChangeType.Inserted:
                    case DiffPlex.DiffBuilder.Model.ChangeType.Imaginary:
                        <text><div class="smallmargin filler"></div></text>
                        break;
                    case DiffPlex.DiffBuilder.Model.ChangeType.Unchanged:
                        <text><div class="smallmargin">@row.Text</div></text>
                        break;
                    default:
                        break;
                }
        }
    }
}

<li class="entry">
    <a asp-controller="Issue" asp-action="ViewTalk" asp-route-id="@Model.Issue.Id">
        <div class="from">
            From
            [@(Model.Issue.Project.ShortProjectId)-@(Model.Issue.Id.ToString().PadLeft(4, '0'))]
            @{
                string statusName = Enum.GetName(typeof(PBug.Data.IssueStatus), Model.Issue.Status);
            }
            (<span class="issue-@(statusName.ToLower())-marker">@statusName</span>)
            <span class="issue">@Model.Issue.Name</span>
        </div>
    </a>
    <div class="date">@DateUtils.StringDate(Model.DateOfOccurance)</div>
    @(Model.Author == null ? "Anonymous" : Model.Author.FullName)

    @if (Model is PostActivity pa)
    {
        <span class="showable-container">
            <a href="javascript:void(0)" class="blue show-button underline">posted</a>
            <div class="showable">
                <div class="postborder">
                    <pre><code class="smallmargin">@pa.ContainedText</code></pre>
                </div>
            </div>
        </span>
    }
    else if (Model is CreateIssueActivity cia)
    {
        <span class="showable-container">
            <a href="javascript:void(0)" class="blue show-button underline">has created issue with description</a>
            <table class="showable hide" style="width:100%">
                <tr>
                    <td class="postborder">
                        <pre><code class="smallmargin">@cia.Description</code></pre>
                    </td>
                </tr>
            </table>
            @if (!string.IsNullOrWhiteSpace(cia.Tags))
            {
                <span class="blue">and with tags</span>
                <span class="taglist">
                    @foreach (var tag in cia.Tags.Split(",", StringSplitOptions.RemoveEmptyEntries))
                    {
                        @:#@tag
                    }
                </span>
            }
            <span class="blue">and with title</span>
            @cia.Name
        </span>
    }
    else if (Model is EditPostActivity epa)
    {
        var diff = DiffHelper.DiffText(epa.OldContainedText, epa.NewContainedText);

        <span class="showable-container">
            <a href="javascript:void(0)" class="blue show-button underline">has edited post</a>
            <table class="showable hide" style="width:100%">
                <tr>
                    <td class="postborder fleft" style="width:48%">
                        <pre><code>@{DisplayDiff(diff.OldText.Lines, true);}</code></pre>
                    </td>
                    <td class="postborder fright" style="width:48%">
                        <pre><code>@{DisplayDiff(diff.NewText.Lines, false);}</code></pre>
                    </td>
                </tr>
            </table>
        </span>        
    }
    else if (Model is EditIssueActivity eia) {
        <span class="showable-container">
            @if (eia.OldDescription != eia.NewDescription) 
            {
                var diff = DiffHelper.DiffText(eia.OldDescription, eia.NewDescription);
                <a href="javascript:void(0)" class="blue show-button underline">edited description</a>
                <table class="showable hide" style="width:100%">
                    <tr>
                         <td class="postborder fleft" style="width:48%">
                            <pre><code>@{DisplayDiff(diff.OldText.Lines, true);}</code></pre>
                        </td>
                        <td class="postborder fright" style="width:48%">
                            <pre><code>@{DisplayDiff(diff.NewText.Lines, false);}</code></pre>
                    </td>
                    </tr>
                </table>
            }
            @if (eia.OldTags != eia.NewTags)
            {
                <span class="blue">changed tags from (</span>
                <span class="taglist">
                    @foreach (var tag in eia.OldTags.Split(',', StringSplitOptions.RemoveEmptyEntries))
                    {
                        <span class="tag">#@tag</span>
                    }
                </span>
                <span class="blue">) to (</span>
                <span class="taglist">
                    @foreach (var tag in eia.NewTags.Split(',',StringSplitOptions.RemoveEmptyEntries))
                    {
                        <span class="tag">#@tag</span>
                    }
                </span>
                <span class="blue">)</span>
            }
            @if (eia.OldDescription != eia.NewDescription)
            {
                <span class="blue">changed title from</span>
                @eia.OldDescription
                <span class="blue">to</span>
                @eia.NewDescription
            }
            @if (eia.OldAssigneeId != eia.NewAssigneeId)
            {
                if (eia.NewAssigneeId == null)
                {
                    <span class="blue">removed assignee</span>
                }
                else
                {
                    <span class="blue">assigned </span>
                    @eia.NewAssignee.FullName
                }
            }
            @if (eia.OldStatus != eia.NewStatus)
            {
                <span class="blue">changed status from</span>
                <span class="issue-@(eia.OldStatus.ToString().ToLower())-marker">@Enum.GetName(typeof(IssueStatus),eia.OldStatus)</span>
                <span class="blue">to</span>
                <span class="issue-@(eia.NewStatus.ToString().ToLower())-marker">@Enum.GetName(typeof(IssueStatus),eia.NewStatus)</span>
            }
        </span>
    }
    else
    {
        <span class="blue">Invalid or unparsable activity</span>
    }
</li>

PBug/Views/Issue/Create.cshtml
@model IssueCreateModel

<form asp-controller="Issue" asp-action="Create" method="POST" enctype="multipart/form-data">
    <input type="text" name="name" placeholder="Title" class="title-input" required>
    <hr>
    <input type="text" class="taglist" name="tags" id="taglist" onkeypress="return event.keyCode != 13;">
    <br>
    <textarea name="firsttext" class="submit-text" placeholder="Description" required></textarea>
    <br>
    <label for="projectchooser">Project: </label>
    <select name="projectid" id="projectchooser" class="blueunderline" required>
        @foreach (var project in @Model.AllProjects)
        {
            <option value="@(project.Id.ToString())">@project.Name (@project.ShortProjectId)</option>
        }
    </select>
    <label for="assigneechooser">Assignee: </label>
    <select name="assigneeid" id="assigneechooser" class="blueunderline">
        <option value="-1">Unassign</option>
        @foreach (var user in @Model.AllUsers)
        {
            <option value="@(user.Id)">@RenderHelpers.ShowUser(user, false)</option>
        }
    </select>
    <input type="file" name="file[]" multiple>
    <br>
    <input type="submit" value="Post" class="submitpost" style="float:right">
</form>

@section Stylesheets
{
    <link rel="stylesheet" href="~/css/jquery.tag-editor.css">
}
@section Scripts
{
    <script src="~/js/jquery.tag-editor.min.js"></script>
    <script>
        $("#taglist").tagEditor({placeholder:"Issue tags"});
        $(document).on("keypress", ".tag-editor", function(event) {
            return event.keyCode != 13;
        });
    </script>
}

PBug/Views/Issue/EditIssue.cshtml
@model IssueEditIssueModel

<form asp-controller="Issue" asp-action="EditIssue" asp-route-id="@Model.Issue.Id" method="POST" enctype="multipart/form-data">
    <input type="hidden" name="filesremoved" value="[]" id="filesremoved">
    <input type="text" name="newtitle" class="title-input" required value="@Model.Issue.Name">
    <hr>
    <input type="text" name="newtags" id="taglist" class="taglist" value="@Model.Issue.Tags" onkeypress="return event.keyCode != 13;">
    <br>
    <textarea name="newtext" placeholder="Description" class="submit-text" required>@Model.Issue.Description</textarea>
    <br>
    <label for="projectchooser">Project: </label>
    <select name="newprojectid" id="projectchooser" class="blueunderline" required>
        @foreach (var project in Model.AllProjects)
        {
            @if (project.Id == Model.Issue.ProjectId)
            {
                <option value="@project.Id" selected>@project.Name (@project.ShortProjectId)</option>
            }
            else
            {
                <option value="@project.Id">@project.Name (@project.ShortProjectId)</option>
            }
        }
    </select>
    <label for="assigneechooser">Assignee: </label>
    <select name="newassigneeid" id="assigneechooser" class="blueunderline" required>
        <option value="-1">Unassign</option>
        @foreach (var user in Model.AllUsers)
        {
            @if (user.Id == Model.Issue.AssigneeId)
            {
                <option value="@user.Id" selected>@RenderHelpers.ShowUser(user, false)</option>
            }
            else
            {
                <option value="@user.Id">@RenderHelpers.ShowUser(user, false)</option>
            }
        }
    </select>
    <label for="statuschooser">Status: </label>
    <select name="newstatusid" id="statuschooser" class="blueunderline" required>
        @foreach (var status in Enum.GetValues(typeof(IssueStatus)).Cast<IssueStatus>())
        {
            @if (status == Model.Issue.Status)
            {
                <option value="@status" selected>@Enum.GetName(typeof(IssueStatus), status)</option>
            }
            else
            {
                <option value="@status">@Enum.GetName(typeof(IssueStatus), status)</option>
            }
        }
    </select>
    <br>
    @foreach (var file in Model.Issue.Files)
    {
        <div class="file">
            <a href="javascript:void(0)" data-uid="@file.FileId" class="sendbutton">X</a>
            <a asp-controller="File" asp-action="Download" asp-route-id="@file.FileId" class="filename">@file.FileName</a>
        </div>
    }
    <br>
    <input type="file" name="file[]" multiple>
    <br>
    <input type="submit" value="Repost" class="submitpost" style="float:right">
</form>

@section Stylesheets
{
    <link rel="stylesheet" href="~/css/jquery.tag-editor.css">
}

@section Scripts
{
    <script src="~/js/jquery.tag-editor.min.js"></script>
    <script>
        $("#taglist").tagEditor({placeholder:"Issue tags"});
        $(document).on("keypress", ".tag-editor", function(event) {
            return event.keyCode != 13;
        });
        function removefile(ev) {
            var uid = $(ev).attr("data-uid");
            var flist = JSON.parse($("#filesremoved").val());
            flist.push(uid);
            $("#filesremoved").val(JSON.stringify(flist));
            $(ev).off("click").click(function() {unremovefile(this)});
            $(ev).parent().children(".filename").addClass("strike");
        }
        function unremovefile(ev) {
            var uid = $(ev).attr("data-uid");
            var flist = JSON.parse($("#filesremoved").val());
            flist.splice(flist.indexOf(uid),1);
            $("#filesremoved").val(JSON.stringify(flist));
            $(ev).off("click").click(function() {removefile(this)});
            $(ev).parent().children(".filename").removeClass("strike");
        }
        $("a.sendbutton").click(function() {removefile(this)});
    </script>
}

PBug/Views/Issue/EditPost.cshtml
@model IssuePost

<form asp-controller="Issue" asp-action="EditPost" asp-route-id="@Model.Id" method="POST" enctype="multipart/form-data">
    <div class="entry">
        <div class="entryauthor">@RenderHelpers.ShowUser(Model.Author)</div>
        <div class="date">@DateUtils.StringDate(Model.DateOfCreation)</div>
        @if (@Model.DateOfEdit != null)
        {
            <div class="date">Edited on @DateUtils.StringDate(Model.DateOfEdit)</div>
        }
        <textarea name="text" class="submit-text">@Model.ContainedText</textarea>
    </div>
    <input type="submit" value="Repost" class="submitpost" style="float:right">
</form>

PBug/Views/Issue/News.cshtml
@model NewsSearchModel

<div class="searchbox">
    <form asp-controller="Issue" asp-action="News" method="GET">
        <input type="text" id="searchbox" placeholder="Search..." name="q" value="@Model.SearchString" class="search">
        <input type="submit" class="submit-search" value="Search" style="background: url(@Url.Content("~/img/magnifying_glass.png")) no-repeat">
    </form>
    <div class="links">
        <a href="javascript:void(0)" onclick="addthing('status:open', ['status:closed'])">open</a>
        /
        <a href="javascript:void(0)" onclick="addthing('status:closed', ['status:open'])">closed</a>
         |  watched:
        <a href="javascript:void(0)" onclick="addthing('watched:yes', ['watched:no'])">yes</a>
        /
        <a href="javascript:void(0)" onclick="addthing('watched:no', ['watched:yes'])">no</a>
         | 
        <a href="javascript:void(0)" onclick="addthing('order:asc', ['order:desc'])">⇧</a>
        <a href="javascript:void(0)" onclick="addthing('order:desc', ['order:asc'])">⇩</a>
    </div>
</div>

<ul class="issues-list">
    @foreach (var activity in @Model.FoundNews)
    {
        <partial name="IssueActivityPartial" model="activity" /> 
    }
</ul>

@section Scripts
{
    <script>
        function addthing(thing,repl) {
            if ($("#searchbox").val().indexOf(thing) === -1) {
                for (var i = 0; i < repl.length; i++) {
                    if ($("#searchbox").val().indexOf(repl[i]) !== -1) {
                        $("#searchbox").val($("#searchbox").val().replace(repl[i],thing));
                        return;
                    }
                }
                $("#searchbox").val($("#searchbox").val() + " " + thing);
            }
            else {
                var data = $("#searchbox").val();
                data = data
                    .replace(" " + thing, "")
                    .replace(thing + " ", "")
                    .replace(thing, "");
                $("#searchbox").val(data);
            }
        }
    </script>
}

PBug/Views/Issue/ViewTalk.cshtml
@model IssueViewModel

@section Stylesheets 
{
    @* FIXME: Somehow do highlighting. *@
    @* <link rel="stylesheet" href="~/css/highlightstyles/default.css"> *@
}

<div class="issue-tag">
    [@(Model.Issue.Project.ShortProjectId)-@(Model.Issue.Id.ToString().PadLeft(4, '0'))]
    @{
        string statusName = Enum.GetName(typeof(PBug.Data.IssueStatus), Model.Issue.Status);
    }
    (<span class="issue-@(statusName.ToLower())-marker">@statusName</span>)
    <span class="assigneetext">@(Model.Issue.Assignee != null ? RenderHelpers.ShowUser(Model.Issue.Assignee) : "No assignee")</span>
    <span class="assigneetext" style="float:right">Author: @RenderHelpers.ShowUser(Model.Issue.Author)</span>
</div>
<h2 class="issue-name">@Model.Issue.Name</h2>
<hr>
<div class="taglist">
    @if (Model.Issue.Tags.Length > 1)
    {
        @foreach (var tag in Model.Issue.Tags.Split(",", StringSplitOptions.RemoveEmptyEntries))
        {
            <span class="tag">#@tag</span>
        }
    }
</div>
<div class="underpanel">
    @if (Context.UserCan("issue.editissue.all")
     || (Context.UserCan("issue.editissue.own") && ((int?)Model.Issue.AuthorId??-1) == Context.User.GetUserId()))
    {
        <a asp-controller="Issue" asp-action="EditIssue" asp-route-id="@Model.Issue.Id">edit</a>
    }
    @if (Context.UserCan("issue.deleteissue"))
    {
        <form asp-controller="Issue" asp-action="DeleteIssue" asp-route-id="@Model.Issue.Id" class="linkform">
            <input type="submit" value="delete issue" class="buttonlink">
        </form>
    }
    @if (!User.IsAnonymous())
    {
        <form asp-controller="Issue" asp-action="ToggleWatch" asp-route-id="@Model.Issue.Id" class="linkform">
            <input type="submit" value="@(Model.IsWatching ? "unwatch" : "watch")" class="buttonlink">
        </form>
    }
    @if (Context.UserCan("issue.activity"))
    {
        <a asp-controller="Issue" asp-action="ViewActivity" asp-route-id="@Model.Issue.Id">activity</a>
    }
    <br>
</div>
<p>@MarkdownHelper.ToHtml(Model.Issue.Description)</p>    
<ul>
    @foreach (var file in Model.Issue.Files)
    {
        <a asp-controller="File" asp-action="Download" asp-route-uid="@file.FileId">@file.FileName</a>
        <br>
    }
</ul>

<ul class="postlist">
    @foreach (var post in Model.Issue.Posts)
    {
        <li class="entry" id=@post.Id>
            <div class="entryauthor">@RenderHelpers.ShowUser(post.Author)</div>
            <div class="date">@DateUtils.StringDate(post.DateOfCreation)</div>
            @if (post.DateOfEdit != null)
            {
                <div class="date">Edited on @DateUtils.StringDate(post.DateOfEdit)</div>
            }
            <div class="comment-underpanel">
                @if (Context.UserCan("issue.editpost.all")
                 || (Context.UserCan("issue.editpost.own") && ((int?)post.AuthorId??-1) == Context.User.GetUserId()))
                {
                    <a asp-controller="Issue" asp-action="EditPost" asp-route-id="@post.Id">edit</a>
                }
                <a asp-controller="Issue" asp-action="ViewTalk" asp-route-id="@Model.Issue.Id" asp-fragment="@post.Id">link to post</a>
            </div>
            @MarkdownHelper.ToHtml(post.ContainedText)
        </li>
    }
    @if (Context.UserCan("issue.post"))
    {
        <li class="entry">
            <form asp-controller="Issue" asp-action="Post" asp-route-id="@Model.Issue.Id" method="POST" enctype="application/x-www-form-urlencoded">
                <div class="entryauthor">
                    @User.GetClaim(ClaimTypes.Name).Value
                    @if (!User.IsAnonymous())
                    {
                        <span class="username">@@@User.GetClaim(ClaimTypes.NameIdentifier).Value</span>
                    }
                </div>
                <div class="date">@DateUtils.StringDate(DateTime.UtcNow)</div>
                <textarea name="text" placeholder="Post contents (Markdown)" class="submit-text"></textarea>
                <br>
                <input type="submit" value="Post" class="submitpost" style="float:right">
                <br>
            </form>
        </li>
    }
</ul>