PBug/Controllers/KnowledgeBaseController.cs
using System.Globalization;
using System.Net.Cache;
using System.Net.Http.Headers;
using System;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PBug.Authentication;
using PBug.Data;
using PBug.Models;
using PBug.Utils;

namespace PBug.Controllers
{
    public class KnowledgeBaseController : Controller
    {
        private readonly PBugContext Db;
        public KnowledgeBaseController(PBugContext ctx)
        {
            Db = ctx;
        }

        [Route("/kb/")]
        public IActionResult Main()
        {
            return RedirectToAction("ViewPage", new { path = "main" });
        }

        [Route("/kb/search")]
        [PBugPermission("kb.search")]
        public async Task<IActionResult> Search([FromQuery] string q)
        {
            if (q == null) q = "";
            KBSearchModel model = new KBSearchModel();
            model.SearchString = q;
            IQueryable<Infopage> searchQuery = Db.Infopages
                .Include(x => x.Author);
            bool orderAscending = true;
            if (!HttpContext.UserCan("kb.secrecy.0"))
                searchQuery = searchQuery.Where(x => x.Secrecy != 0);
            if (!HttpContext.UserCan("kb.secrecy.1"))
                searchQuery = searchQuery.Where(x => x.Secrecy != 1);
            if (!HttpContext.UserCan("kb.secrecy.2"))
                searchQuery = searchQuery.Where(x => x.Secrecy != 2);
            if (!HttpContext.UserCan("kb.secrecy.3"))
                searchQuery = searchQuery.Where(x => x.Secrecy != 3);

            foreach (string sub in q.Split(' ', StringSplitOptions.RemoveEmptyEntries))
            {
                if (sub.StartsWith("#"))
                {
                    string tagName = sub.Substring(1);
                    searchQuery = searchQuery.Where(x => x.Tags.Contains(tagName));
                }
                else if (sub.StartsWith("author:"))
                {
                    string authorName = sub.Substring("author:".Length);
                    if (authorName == "me")
                    {
                        searchQuery = searchQuery.Where(x => x.Author.Id == HttpContext.User.GetUserId());
                    }
                    else
                    {
                        searchQuery = searchQuery.Where(x => x.Author.Username == authorName);
                    }
                }
                else if (sub.StartsWith("order:"))
                {
                    string order = sub.Substring("order:".Length);
                    if (!Regex.IsMatch(order, ".*asc.*"))
                        orderAscending = false;
                }
                else
                {
                    searchQuery = searchQuery.Where(x => x.Name.Contains(sub));
                }
            }
            if (orderAscending)
                searchQuery = searchQuery.OrderBy(x => x.Id);
            else
                searchQuery = searchQuery.OrderByDescending(x => x.Id);

            model.FoundInfopages = await searchQuery.ToArrayAsync();

            return View(model);
        }

        [Route("/kb/create/{*path}")]
        [HttpGet]
        [PBugPermission("kb.create")]
        public IActionResult Create(string path)
        {
            return View((object)(path.Replace("%2F", "/", true, CultureInfo.InvariantCulture)));
        }

        [Route("/kb/create/{*path}")]
        [HttpPost]
        [PBugPermission("kb.create")]
        public async Task<IActionResult> Create([FromRoute] string path, CreatePageRequest req)
        {
            if (!ModelState.IsValid)
                return View((object)(path.Replace("%2F", "/", true, CultureInfo.InvariantCulture)));
            if (!HttpContext.UserCan("kb.secrecy." + ((byte)req.Secrecy).ToString()))
                return Forbid();
            var page = (await Db.Infopages.AddAsync(new Infopage()
            {
                AuthorId = HttpContext.User.IsAnonymous() ? null : new uint?((uint)HttpContext.User.GetUserId()),
                EditorId = HttpContext.User.IsAnonymous() ? null : new uint?((uint)HttpContext.User.GetUserId()),
                DateOfCreation = DateTime.UtcNow,
                DateOfEdit = DateTime.UtcNow,
                Path = path.Replace("%2F", "/", true, CultureInfo.InvariantCulture),
                Name = req.Name,
                Tags = req.Tags ?? "",
                ContainedText = req.Text,
                Secrecy = (byte)req.Secrecy
            })).Entity;

            await Db.KBActivities.AddKBActivity(HttpContext, 0, new CreatePageActivity()
            {
                Infopage = page,
                Name = req.Name,
                ContainedText = req.Text,
                Tags = req.Tags ?? "",
                Secrecy = (int?)req.Secrecy
            });

            await Db.SaveChangesAsync();

            return RedirectToAction("ViewPage", new
            {
                path = path.Replace("%2F", "/", true, CultureInfo.InvariantCulture)
            });
        }

        [Route("/kb/view/{*path}")]
        [PBugPermission("kb.view")]
        public async Task<IActionResult> ViewPage([FromRoute] string path)
        {
            Infopage page = await Db.Infopages
                .Include(x => x.Author)
                .SingleOrDefaultAsync(x => x.Path == path.Replace("%2F", "/", true, CultureInfo.InvariantCulture));

            if (page == null)
                return View("NoPage", path.Replace("%2F", "/", true, CultureInfo.InvariantCulture));
            if (!HttpContext.UserCan("kb.secrecy." + page.Secrecy.ToString()))
                return Forbid();

            return View(page);
        }

        [Route("/kb/edit/{*path}")]
        [HttpGet]
        public async Task<IActionResult> EditPage([FromRoute] string path)
        {
            var page = await Db.Infopages.SingleAsync(x => x.Path == path.Replace("%2F", "/", true, CultureInfo.InvariantCulture));
            if (!HttpContext.UserCan("kb.editpage.all")
            && !(HttpContext.UserCan("kb.editpage.own") && ((int?)page.AuthorId ?? -1) == HttpContext.User.GetUserId()))
            {
                if (HttpContext.User.IsAnonymous())
                    return Challenge();
                else
                    return Forbid();
            }
            if (!HttpContext.UserCan("kb.secrecy." + page.Secrecy.ToString()))
                return Forbid();
            return View(page);
        }

        [Route("/kb/edit/{*path}")]
        [HttpPost]
        public async Task<IActionResult> EditPage([FromRoute] string path, CreatePageRequest req)
        {
            Infopage page = await Db.Infopages.SingleAsync(x => x.Path == path.Replace("%2F", "/", true, CultureInfo.InvariantCulture));
            if (!HttpContext.UserCan("kb.editpage.all")
            && !(HttpContext.UserCan("kb.editpage.own") && ((int?)page.AuthorId ?? -1) == HttpContext.User.GetUserId()))
            {
                if (HttpContext.User.IsAnonymous())
                    return Challenge();
                else
                    return Forbid();
            }

            if (!ModelState.IsValid)
                return View(page);

            if (!HttpContext.UserCan("kb.secrecy." + page.Secrecy.ToString()))
                return Forbid();
            if (!HttpContext.UserCan("kb.secrecy." + ((byte)req.Secrecy).ToString()))
                return Forbid();

            await Db.KBActivities.AddKBActivity(HttpContext, page.Id, new EditPageActivity()
            {
                OldName = page.Name,
                NewName = req.Name,
                OldTags = page.Tags,
                NewTags = req.Tags ?? "",
                OldContainedText = page.ContainedText,
                NewContainedText = req.Text,
                OldSecrecy = page.Secrecy,
                NewSecrecy = (byte)req.Secrecy
            });

            page.Name = req.Name;
            page.Tags = req.Tags ?? "";
            page.ContainedText = req.Text;
            page.Secrecy = (byte)req.Secrecy;

            await Db.SaveChangesAsync();

            return RedirectToAction("ViewPage", new { path = path.Replace("%2F", "/", true, CultureInfo.InvariantCulture) });
        }

        [Route("/kb/talk/{*path}")]
        [PBugPermission("kb.talk")]
        public async Task<IActionResult> ViewTalk([FromRoute] string path)
        {
            var page = await Db.Infopages
                .Include(x => x.Comments)
                    .ThenInclude(x => x.Author)
                .SingleAsync(x => x.Path == path.Replace("%2F", "/", true, CultureInfo.InvariantCulture));
            if (!HttpContext.UserCan("kb.secrecy." + page.Secrecy.ToString()))
                return Forbid();
            return View(page);
        }

        [Route("/kb/activity/{*path}")]
        [PBugPermission("kb.activity")]
        public async Task<IActionResult> ViewActivity([FromRoute] string path)
        {
            var page = await Db.Infopages
                .Include(x => x.Activities)
                    .ThenInclude(x => x.Author)
                .SingleAsync(x => x.Path == path.Replace("%2F", "/", true, CultureInfo.InvariantCulture));
            if (!HttpContext.UserCan("kb.secrecy." + page.Secrecy.ToString()))
                return Forbid();
            return View(page);
        }

        [Route("/kb/comment/{*path}")]
        [HttpPost]
        [PBugPermission("kb.comment")]
        public async Task<IActionResult> Comment([FromRoute] string path, CommentPostRequest req)
        {
            if (!ModelState.IsValid)
                return Forbid();
            var page = await Db.Infopages.SingleAsync(x => x.Path == path.Replace("%2F", "/", true, CultureInfo.InvariantCulture));
            if (!HttpContext.UserCan("kb.secrecy." + page.Secrecy.ToString()))
                return Forbid();

PBug/Views/KnowledgeBase/Create.cshtml
@model string

<div class="issue-tag">/@Model</div>
<form asp-controller="KnowledgeBase" asp-action="Create" asp-route-path="@Model" method="POST" enctype="application/x-www-form-urlencoded">
    <input type="text" class="title-input" name="name" placeholder="Title" required>
    <hr>
    <input type="text" class="taglist" name="tags" id="taglist" onkeypress="return event.keyCode != 13;">
    <br>
    <textarea name="text" required placeholder="Text" class="submit-text"></textarea>
    <br>
    <label for="secrecychooser">Secrecy: </label>
    <select name="secrecy" id="secrecychooser" class="blueunderline" required>
        @for (int i = 0; i < 4; i++)
            @if (Context.UserCan("kb.secrecy." + i.ToString()))
            {
                <option value="@i">@Enum.GetName(typeof(KBSecrecy), (KBSecrecy)i)</option>
            }
    </select>
    <input type="submit" value="Post" class="submitpost" style="float:right">
</form>

@section Stylesheets
{
    <link rel="stylesheet" href="~/css/jquery.tag-editor.css">
}
@section Scripts
{
    <script src="~/js/jquery.tag-editor.min.js"></script>
    <script>
        $("#taglist").tagEditor({placeholder:"Issue tags"});
        $(document).on("keypress", ".tag-editor", function(event) {
            return event.keyCode != 13;
        });
    </script>
}

PBug/Views/KnowledgeBase/EditComment.cshtml
@model InfopageComment
@Html.ValidationSummary(false, "", new {})

<h2>Editing Comment</h2>

<form asp-controller="KnowledgeBase" asp-action="EditComment" asp-route-id="@Model.Id" method="POST" enctype="application/x-www-form-urlencoded">
    <div class="entry">
        <div class="entryauthor">@RenderHelpers.ShowUser(Model.Author)</div>
        <div class="date">@DateUtils.StringDate(Model.DateOfCreation)</div>
        @if (Model.DateOfEdit != null)
        {
            <div class="date">Edited on @DateUtils.StringDate(Model.DateOfEdit)</div>
        }
        <textarea name="text" class="submit-text">@Model.ContainedText</textarea>
    </div>
    <input type="submit" value="Repost" class="submitpost" style="float:right">
</form>

PBug/Views/KnowledgeBase/EditPage.cshtml
@model Infopage

<div class="issue-tag">@Model.Path</div>
<form asp-controller="KnowledgeBase" asp-action="EditPage" method="POST" enctype="application/x-www-form-urlencoded">
    <input type="text" name="name" value="@Model.Name" class="h2 blueunderline issue-name" style="width:100%">
    <input type="text" name="tags" value="@Model.Tags" id="taglist" class="taglist">
    <br>
    <div class="entry">
        <textarea name="text" class="submit-text">@Model.ContainedText</textarea>
    </div>
    <label for="secrecychooser">Secrecy: </label>
    <select name="secrecy" id="secrecychooser" class="blueunderline" required>
        @for (int i = 0; i < 4; i++)
            @if (Context.UserCan("kb.secrecy." + i.ToString()))
                @if (Model.Secrecy == i)
                {
                    <option value="@i" selected>@Enum.GetName(typeof(KBSecrecy), (KBSecrecy)i)</option>
                }
                else 
                {
                    <option value="@i">@Enum.GetName(typeof(KBSecrecy), (KBSecrecy)i)</option>
                }
            
    </select>
    <input type="submit" value="Repost" class="submitpost" style="float:right">
</form>

@section Stylesheets
{
    <link rel="stylesheet" href="~/css/jquery.tag-editor.css">
}
@section Scripts
{
    <script src="~/js/jquery.tag-editor.min.js"></script>
    <script>
        $("#taglist").tagEditor({placeholder:"Issue tags"});
        $(document).on("keypress", ".tag-editor", function(event) {
            return event.keyCode != 13;
        });
    </script>
}

PBug/Views/KnowledgeBase/NoPage.cshtml
@model string

<h2 style="text-align:center">404 Infopage Not Found</h2>
An infopage with that path does not exist.
@if (Context.UserCan("kb.create"))
{
    <a asp-controller="KnowledgeBase" asp-action="Create" asp-route-path="@Model">You can create it, however.</a>
}

PBug/Views/KnowledgeBase/Search.cshtml
@model KBSearchModel

<div class="searchbox">
    <form asp-controller="KnowledgeBase" asp-action="Search" method="GET">
        <input type="text" id="searchbox" placeholder="Search..." name="q" value="@Model.SearchString" class="search">
        <input type="submit" class="submit-search" value="Search" style="background: url(@Url.Content("~/img/magnifying_glass.png")) no-repeat">
    </form>
    <div class="links">
        <a href="javascript:void(0)" onclick="addthing('order:asc', ['order:desc'])">⇧</a>
        <a href="javascript:void(0)" onclick="addthing('order:desc', ['order:asc'])">⇩</a>
    </div>
</div>

<ul class="issues-list">
    @foreach (var infopage in @Model.FoundInfopages)
    {
        <li>
            <a asp-controller="KnowledgeBase" asp-action="ViewPage" asp-route-path="@infopage.Path">
                <div class="issue-tag">
                    [/@infopage.Path]
                    <span class="assigneetext">Author: @RenderHelpers.ShowUser(infopage.Author, false)</span>
                </div>
                @infopage.Name
            </a>
        </li>
    }
</ul>

@section Scripts
{
    <script>
        function addthing(thing,repl) {
            if ($("#searchbox").val().indexOf(thing) === -1) {
                for (var i = 0; i < repl.length; i++) {
                    if ($("#searchbox").val().indexOf(repl[i]) !== -1) {
                        $("#searchbox").val($("#searchbox").val().replace(repl[i],thing));
                        return;
                    }
                }
                $("#searchbox").val($("#searchbox").val() + " " + thing);
            }
            else {
                var data = $("#searchbox").val();
                data = data
                    .replace(" " + thing, "")
                    .replace(thing + " ", "")
                    .replace(thing, "");
                $("#searchbox").val(data);
            }
        }
    </script>
}

PBug/Views/KnowledgeBase/ViewActivity.cshtml
@model Infopage

@section Stylesheets 
{
    @* FIXME: Somehow do highlighting. *@
    @* <link rel="stylesheet" href="~/css/highlightstyles/default.css"> *@
}

<div class="issue-tag">/@Model.Path</div>
<div class="issue-tag">
    <div class="date">Authored by @RenderHelpers.ShowUser(Model.Author) on @DateUtils.StringDate(Model.DateOfCreation)</div>
    <div class="date">Edited on @DateUtils.StringDate(Model.DateOfEdit)</div>
</div>
<h2 class="issue-name">@Model.Name</h2>
<hr>
<div class="underpanel">
    @if (Context.UserCan("kb.talk"))
    {
        <a asp-controller="KnowledgeBase" asp-action="ViewTalk" asp-route-path="@Model.Path">talk</a>
    }
    @if (Context.UserCan("kb.view"))
    {
        <a asp-controller="KnowledgeBase" asp-action="ViewPage" asp-route-path="@Model.Path">view</a>
    }
    @if (Context.UserCan("kb.editpage.all")
     || (Context.UserCan("kb.editpage.own") && ((int?)Model.AuthorId??-1)  == Context.User.GetUserId()))
    {
        <a asp-controller="KnowledgeBase" asp-action="EditPage" asp-route-path="@Model.Path">edit</a>
    }
    @if (Context.UserCan("kb.deletepage"))
    {
        <form asp-controller="KnowledgeBase" asp-action="DeletePage" asp-route-path="@Model.Path" class="linkform">
            <input type="submit" value="delete" class="buttonlink">
        </form>
    }
    <br>
</div>
<div class="taglist">
    @if (Model.Tags.Length > 1)
    {
        @foreach (var tag in Model.Tags.Split(",", StringSplitOptions.RemoveEmptyEntries))
        {
            <span class="tag">#@tag</span>
        }
    }
</div>

<ul class="postlist">
    @foreach (var activity in Model.Activities)
    {
        <partial name="KBActivityPartial" model="activity" /> 
    }
</ul>

@section Scripts
{
    <script src="~/js/expandable.js"></script>
}

PBug/Views/KnowledgeBase/ViewPage.cshtml
@model Infopage

<div class="issue-tag">/@Model.Path</div>
<div class="issue-tag">
    <div class="date">Authored by @RenderHelpers.ShowUser(Model.Author) on @DateUtils.StringDate(Model.DateOfCreation)</div>
    <div class="date">Edited on @DateUtils.StringDate(Model.DateOfEdit)</div>
</div>
<h2 class="issue-name">@Model.Name</h2>
<hr>
<div class="underpanel">
    @if (Context.UserCan("kb.talk"))
    {
        <a asp-controller="KnowledgeBase" asp-action="ViewTalk" asp-route-path="@Model.Path">talk</a>
    }
    @if (Context.UserCan("kb.activity"))
    {
        <a asp-controller="KnowledgeBase" asp-action="ViewActivity" asp-route-path="@Model.Path">activity</a>
    }
    @if (Context.UserCan("kb.editpage.all")
     || (Context.UserCan("kb.editpage.own") && ((int?)Model.AuthorId??-1)  == Context.User.GetUserId()))
    {
        <a asp-controller="KnowledgeBase" asp-action="EditPage" asp-route-path="@Model.Path">edit</a>
    }
    @if (Context.UserCan("kb.deletepage"))
    {
        <form asp-controller="KnowledgeBase" asp-action="DeletePage" asp-route-path="@Model.Path" class="linkform">
            <input type="submit" value="delete" class="buttonlink">
        </form>
    }
</div>
<div class="taglist">
    @foreach (var tag in Model.Tags.Split(',', StringSplitOptions.RemoveEmptyEntries))
    {
        <span class="tag">#@tag</span>
    }
</div>
<div class="entry">@MarkdownHelper.ToHtml(Model.ContainedText)</div>

PBug/Views/KnowledgeBase/ViewTalk.cshtml
@model Infopage

<div class="issue-tag">/@Model.Path</div>

<h2 class="issue-name">@Model.Name</h2>
<hr>
<div class="underpanel">
    @if (Context.UserCan("kb.view"))
    {
        <a asp-controller="KnowledgeBase" asp-action="ViewPage" asp-route-path="@Model.Path">view</a>
    }
    @if (Context.UserCan("kb.activity"))
    {
        <a asp-controller="KnowledgeBase" asp-action="ViewActivity" asp-route-path="@Model.Path">activity</a>
    }
    @if (Context.UserCan("kb.editpage.all")
     || (Context.UserCan("kb.editpage.own") && ((int?)Model.AuthorId??-1) == Context.User.GetUserId()))
    {
        <a asp-controller="KnowledgeBase" asp-action="EditPage" asp-route-path="@Model.Path">edit</a>
    }
    @if (Context.UserCan("kb.deletepage"))
    {
        <form asp-controller="KnowledgeBase" asp-action="DeletePage" asp-route-path="@Model.Path" class="linkform">
            <input type="submit" value="delete" class="buttonlink">
        </form>
    }
</div>

<ul class="postlist">
    @foreach (var comment in @Model.Comments)
    {
        <li class="entry" id="@comment.Id">
            <div class="entryauthor">@RenderHelpers.ShowUser(comment.Author)</div>
            <div class="date">@DateUtils.StringDate(comment.DateOfCreation)</div>
            @if (comment.DateOfEdit != null)
            {
                <div class="date">Edited on @DateUtils.StringDate(comment.DateOfEdit)</div>
            }
            <div class="comment-underpanel">
               @if (Context.UserCan("kb.editcomment.all")
                || (Context.UserCan("kb.editcomment.own") && ((int?)comment.AuthorId??-1) == Context.User.GetUserId()))
                {
                    <a asp-controller="KnowledgeBase" asp-action="EditComment" asp-route-id="@comment.Id">edit</a>
                }
                <a asp-controller="KnowledgeBase" asp-action="ViewTalk" asp-route-path="@Model.Path" asp-fragment="@comment.Id">link to comment</a>
            </div>
            @MarkdownHelper.ToHtml(comment.ContainedText)
        </li>
    }

    @if (Context.UserCan("kb.comment"))
    {
        <li class="entry">
            <form asp-controller="KnowledgeBase" asp-action="Comment" asp-route-path="@Model.Path" method="POST" enctype="application/x-www-form-urlencoded">
                <div class="entryauthor">
                    @User.GetClaim(ClaimTypes.Name).Value
                    @if (!User.IsAnonymous())
                    {
                        <span class="username">@@@User.GetClaim(ClaimTypes.NameIdentifier).Value</span>
                    }
                </div>
                <div class="date">@DateUtils.StringDate(DateTime.UtcNow)</div>
                <textarea name="text" placeholder="Comment contents (Markdown)" class="submit-text"></textarea>
                <br>
                <input type="submit" value="Post" class="submitpost" style="float:right">
                <br>
            </form>
        </li>
    }
</ul>